# questions.py

questions = [
    "What are the three fundamental questions all IT support stems from?",
    "Why is 'How did the problem begin?' considered the most important question?",
    "What is the most basic principle of IT support mentioned in Chapter 1?",
    "Why should an IT professional always ask 'What's changed?'",
    "What is the definition of a 'numpty' in the context of IT support?",
    "Why is a computer left in its box considered 'problem-free'?",
    "How can a tiny change in a model number (like an added 'S') affect IT support?",
    "What is the 'Language Barrier' in IT support?",
    "Why is the 'Human Factor' considered complex in IT troubleshooting?",
    "What are the six steps for approaching communications with a user?",
    "Why should you assume a user has no technical knowledge initially?",
    "Why is it beneficial to ask 'Yes/No' questions during a diagnosis?",
    "What is the purpose of asking a user to repeat instructions back to you?",
    "Name three types of devices besides PCs that an IT professional might encounter.",
    "When does official support for Windows 7 end?",
    "When does official support for Windows 8.1 end?",
    "How often are 'feature packs' for Windows 10 typically released?",
    "What is the 'Long Term Servicing Channel' (LTSC) in Windows 10?",
    "How long does Apple typically support OS X and iOS versions?",
    "Why is 'interconnectedness' a challenge for modern IT systems?",
    "What is 'Flow Logic' in the context of troubleshooting?",
    "Why is the 'Process of Elimination' critical in IT support?",
    "What does it mean to 'Begin at the End' when diagnosing a problem?",
    "How can asset tag and installation date data reduce support workload?",
    "Why is it important to never make assumptions during teaching or support?",
    "How can an IT professional gauge a user's level of technical expertise?",
    "What is the 'Non-technical Dictionary'?",
    "If a user points to a monitor when asked for their computer, what should you do?",
    "How does online chat differ from phone support in terms of user querying?",
    "What is the 'Root Cause' of an IT issue?",
    "Why is troubleshooting described as a 'holistic process'?",
    "What are 'dots' in the context of 'joining the dots'?",
    "Why is it important to take a break from a complex problem?",
    "How can small steps and small checks eliminate possible causes?",
    "What is the role of diplomacy in IT support?",
    "Why do users sometimes find satisfaction in learning what they did wrong?",
    "What is the 'endorphin hit' associated with solving an IT puzzle?",
    "How does the 'murder mystery' analogy apply to IT diagnostics?",
    "Why should paperwork allow anyone to 'run with' a job in progress?",
    "What is the primary goal of creating quality paperwork?",
    "How are modern IT systems structured differently from legacy systems?",
    "Why is hardware sometimes the 'last cause' of a problem?",
    "What can cause a PC to turn on briefly and then shut off?",
    "How does an aging power supply affect a computer?",
    "Name three external factors that can cause hardware failure.",
    "What is a UPS and why is it used?",
    "How do environmental factors like dust or moisture affect IT systems?",
    "What are common reasons why users 'screw up' IT systems?",
    "How can software settings lead to IT support calls?",
    "What is the 'Monkey Mind' in the context of the human factor?",
    "What challenges do legacy devices present to modern operating systems?",
    "What is a device driver?",
    "How do you troubleshoot device driver errors?",
    "What are the common issues associated with USB peripherals?",
    "How do buildings and city/countryside locations affect Wi-Fi and cellular signals?",
    "What is 'IT and Accessibility'?",
    "How do Windows updates sometimes interfere with hardware compatibility?",
    "Why is it difficult to support software users installed themselves?",
    "What 'headaches' can developers (devs) cause for IT support?",
    "What is the 'upshot' of living in the internet age for IT support?",
    "Why does good documentation save a business time and money?",
    "How does documentation assist in staff training?",
    "What does 'dumbing things down' mean in documentation?",
    "What is the 'KISS' principle in IT support?",
    "Why should troubleshooting guides be 'clean and concise'?",
    "What are the three levels of support paperwork mentioned?",
    "What is 'First-Line Support Paperwork'?",
    "What is the difference between second- and third-line support paperwork?",
    "Why is a 'Why?' box for every question in paperwork counter-productive?",
    "What is the value of 'Extra information' sections in forms?",
    "What are the three reasons for knowing the resolution of a case?",
    "How does documentation help with client billing?",
    "What is a 'repository' of IT data?",
    "How can case reviews improve future workflows?",
    "What is the 'Reliability History' tool in Windows?",
    "What information can be found in 'System Information' on a PC?",
    "What is the 'Performance Monitor' used for?",
    "How do you use the 'Event Viewer' to diagnose errors?",
    "What are the different tabs in the 'Task Manager'?",
    "How can you connect to the event log on another PC?",
    "What is 'Remote Desktop'?",
    "How does 'Quick Assist' help in providing remote support?",
    "Name two third-party remote support tools.",
    "What is an 'Asset Tag' and why is it used in remote gathering?",
    "How do you permit remote administration on a Windows PC?",
    "What is the risk of signing into the registry as another user?",
    "What is the Microsoft Management Console (MMC)?",
    "How can you use MMC remotely?",
    "What is the 'Problem Steps Recorder'?",
    "How do screenshots help in troubleshooting?",
    "What is 'Screencasting'?",
    "How can the Xbox Game Bar be used for IT support?",
    "What are '.dmp' files?",
    "Where can you find other Windows error logs besides the Event Viewer?",
    "What are ETL log files?",
    "How do you copy and save event details for later analysis?",
    "What is 'Reliability History' used for in advanced diagnostics?",
    "Why is 'Écouter et Répéter' mentioned in training?",
    "What are the 'administrative tools' in Windows?",
    "How does a step-by-step approach benefit troubleshooting device drivers?",
]
