services:
  postgres:
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-U",
          "${DATABASE_USER}",
          "-d",
          "${DATABASE_NAME}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-db:/var/lib/postgresql/data
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest-full
    container_name: mlflow_server
    ports:
      - "5000:5000"
    environment:
      - BACKEND_STORE_URI=postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@postgres:${DATABASE_PORT}/${DATABASE_NAME}
      - ARTIFACT_ROOT=/mlflow/artifacts
    volumes:
      - mlflow-artifacts:/mlflow/artifacts
    command: >
      /bin/sh -c "pip install psycopg2-binary --quiet &&
      mlflow server
      --backend-store-uri postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@postgres:${DATABASE_PORT}/${DATABASE_NAME}
      --default-artifact-root /mlflow/artifacts
      --host 0.0.0.0
      --allowed-hosts '*'"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "timeout 1s bash -c ':> /dev/tcp/127.0.0.1/5000' || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      postgres:
        condition: service_healthy

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: it-support-rag-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_PORT=${DATABASE_PORT}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - FRONTEND_URL=${FRONTEND_URL}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - HF_TOKEN=${HF_TOKEN}
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI}
    volumes:
      - mlflow-data:/code/mlflow_data
      - mlflow-artifacts:/code/mlflow_artifacts
    depends_on:
      postgres:
        condition: service_healthy
      mlflow:
        condition: service_healthy
volumes:
  postgres-db:
  mlflow-data:
  mlflow-artifacts:
