name: Linting

on:
  pull_request:

jobs:
  ruff:
    name: Ruff Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Ruff
        uses: astral-sh/ruff-action@v1
        with:
          args: check --output-format=github
